name: installDependencies
on: workflow_call
jobs: 
    InstallDependencies:
        runs-on: ubuntu-latest
        steps:    
          - name: Get Code
            uses: actions/checkout@v3
          - name: Get Directory Listing
            run: ls -R
          - name: Install NodeJS
            uses: actions/setup-node@v3
            with:
                node-version: 20
          - name: Cache dependencies
            id: cache
            uses: actions/cache@v4
            with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies                
            run: npm ci 
    