name: FirstWorkflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main    
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:    
      - name: Get Code
        uses: actions/checkout@v3
      - name: Get Directory Listing
        run: ls -R
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies                
        run: npm ci 
      - name: Run tests
        id: run-tests
        run: npx ng test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'        
        uses: actions/upload-artifact@v7
        with: 
          name: test-report 
          path: test-files            
  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            dist
            package.json
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3 
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        continue-on-error: true
      - name: run linter
        id: run-linter
        run: npm run lint 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: lint-files                
  deploy:
    needs: build
    runs-on: ubuntu-latest    
    steps:  
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with: 
          name: dist-files         
      - name: Deploy
        run: echo "Deploying ..."   
  report:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        if: failure() && steps.run-tests.outcome == 'failure'
        run: |
          echo "Something went wrong."
          echo ${{ toJSON(github) }}
      - name: Download Linter artifacts
        if: failure() && steps.run-linter.outcome == 'failure'        
        uses: actions/download-artifact@v7
        with: 
          name: lint-files   
