name: FirstWorkflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main    
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:    
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies        
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v7
        with: 
          name: dist-files          
      - name: Deploy
        run: echo "Deploying ..."   
